# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./dumps:/dumps
    environment:
      MYSQL_ROOT_PASSWORD: testtest
